language: node_js
node_js: node
deploy:
  provider: heroku
  app: secure-everglades-61988
  api_key:
    secure: cMJVtDlMe4SygxiQedFOMjteVb2NZu9BSMo1f/F+trpBtrYxwEjLQqo1nTBWnyaMOjHnRXa31kTtWdVYfSq4Q5dh63fDL45voP349K0ZTwzkoYWXcNqAvOrJypRITI1zfgcs7mJz5FOJJx/jCYlM8kDt9rWQSoDMUwhaF6P63B0SyiytOHCXxYImt+xblmXsPihrkjtOFlPNXhdIAAbdQxudL+aHGW527cGqZza+UyxrLrWAVGRrZBb8E96E8LKG84Wy3SCub2Q0CRmR4AXALubPUsv3UgzRCi2hlSvQYXnSALjCfjMvJHDJi8rhixYMiGBO7aeuAkYu4z18/NLDJBf/l+QdOAwhzLfLXWuCBerg6BWZqtlyocDRsVocrrGIVQB6Yvrny97iHh++xSjEZIhm8eBB/AP272G1jYXWxqt0zbSkXTLoz33VJS5//HETwLjw0Dqt8BaeWkB3Fb26S4PTwbhQw89RzGW/0I8uU6JvpizRGTBPkILsijBDqiZjKT+R99Tn8g27JL6fsiGw5SumMxiMeKIYj8sFzoyO1puW85VqL3jWB6fZjw4AxEC4FZc6BdWtj7q3sVAy2xen4vmOzN55nPoU4cC9dqOdT9XHfx0GX39Gxs7qnlbXRd5rPYz25qF/juqhox9KjO/9PtRUeGOioPR95KmXQiIs3F0=
